### ISSUE TITLE
Ignoring unknown function 'import' in file catchnhole/catchnhole.scad

### ISSUE THREAD

**Issue by harrison-drift** [mmalecki/catchnhole#3]
Seems to be an issue with the YAML library.

```bash
/node_modules/yaml/dist/public-api.js:73
            throw doc.errors[0];
            ^

YAMLParseError: Map keys must be unique at line 419, column 13:

      types:
            ^
```

Also noticed the readme doesn't mention that you need to npm install and run the build script for the module to register.

**Comment by harrison-drift** [comment]
I'm a muppet.

> catchnhole uses OpenSCAD's JSON import, which is only present in the nightly build, and must be enabled.

If you're having this issue, go get the OpenSCAD nightly.

**Comment by mmalecki** [comment]
I took a look at the README, and while this instruction is there, it's very easy to miss indeed. Let me give that notice some more real estate :)

**Comment by harrison-drift** [comment]
Totally by bad, I just skimmed the readme to see the functions without actually _reading it._ 😅
